#pragma once

namespace gamescope
{
	enum GamescopeKnownDisplays
	{
		GAMESCOPE_KNOWN_DISPLAY_UNKNOWN,
		GAMESCOPE_KNOWN_DISPLAY_STEAM_DECK_LCD,      // Jupiter
		GAMESCOPE_KNOWN_DISPLAY_STEAM_DECK_OLED_SDC, // Galileo SDC
		GAMESCOPE_KNOWN_DISPLAY_STEAM_DECK_OLED_BOE, // Galileo BOE
	};

	enum GamescopeModeGeneration
	{
		GAMESCOPE_MODE_GENERATE_CVT,
		GAMESCOPE_MODE_GENERATE_FIXED,
	};

	enum GamescopeScreenType
	{
		GAMESCOPE_SCREEN_TYPE_INTERNAL,
		GAMESCOPE_SCREEN_TYPE_EXTERNAL,

		GAMESCOPE_SCREEN_TYPE_COUNT
	};
}

enum GamescopeAppTextureColorspace
{
	GAMESCOPE_APP_TEXTURE_COLORSPACE_LINEAR = 0,
	GAMESCOPE_APP_TEXTURE_COLORSPACE_SRGB,
	GAMESCOPE_APP_TEXTURE_COLORSPACE_SCRGB,
	GAMESCOPE_APP_TEXTURE_COLORSPACE_HDR10_PQ,
	GAMESCOPE_APP_TEXTURE_COLORSPACE_PASSTHRU,
};
const uint32_t GamescopeAppTextureColorspace_Bits = 3;

inline bool ColorspaceIsHDR( GamescopeAppTextureColorspace colorspace )
{
	return colorspace == GAMESCOPE_APP_TEXTURE_COLORSPACE_SCRGB ||
		colorspace == GAMESCOPE_APP_TEXTURE_COLORSPACE_HDR10_PQ;
}

